### PR TITLE
script for font subsetting

### PR DESCRIPTION
**Pull request by insualk**
need `pip install fonttools`

### CODE REVIEW

**Comment by ztl8702** [comment]
input_text 要删掉。你留个Markdown文件写一下步骤吧。

**Comment by ztl8702** [comment]
`subsetting/preview` 可以整个目录 gitignore 掉？

**Comment by ztl8702** [comment]
@insualk  are you going to continue working on this? I can take over if you want.

**Comment by insualk** [comment]
> @insualk are you going to continue working on this? I can take over if you want.

Sorry I was busy with my final this month. Let me wrap this up real quick.

**Comment by ztl8702** [comment]
Looks good to me. Thanks!

**Pull request merged**
